In [1]:
pwd

'/scratch/hw1666/final_projects/dl4med/explore_data'

In [2]:
root_path = "/scratch/hw1666/final_projects/dl4med/data"

In [3]:
import numpy as np
import pandas as pd

# Explore train.csv

In [4]:
train_csv_name = "/train.csv"

In [5]:
# read the train.csv file
with open(root_path+train_csv_name, "rt") as fin:
    train_csv = pd.read_csv(fin)

In [6]:
train_csv

Path     Sex  Age  \
0       CheXpert-v1.0-small/train/patient00001/study1/...  Female   68   
1       CheXpert-v1.0-small/train/patient00002/study2/...  Female   87   
2       CheXpert-v1.0-small/train/patient00002/study1/...  Female   83   
3       CheXpert-v1.0-small/train/patient00002/study1/...  Female   83   
4       CheXpert-v1.0-small/train/patient00003/study1/...    Male   41   
5       CheXpert-v1.0-small/train/patient00004/study1/...  Female   20   
6       CheXpert-v1.0-small/train/patient00004/study1/...  Female   20   
7       CheXpert-v1.0-small/train/patient00005/study1/...    Male   33   
8       CheXpert-v1.0-small/train/patient00005/study1/...    Male   33   
9       CheXpert-v1.0-small/train/patient00005/study2/...    Male   33   
10      CheXpert-v1.0-small/train/patient00005/study2/...    Male   33   
11      CheXpert-v1.0-small/train/patient00006/study1/...  Female   42   
12      CheXpert-v1.0-small/train/patient00007/study1/...    Male   69   
13      CheXpert-v1.0-small/train/patient00007/study2/...    Male   69   
14      CheXpert-v1.0-small/train/patient00008/study1/...    Male   81   
15      CheXpert-v1.0-small/train/patient00008/study2/...    Male   81   
16      CheXpert-v1.0-small/train/patient00009/study1/...    Male   76   
17      CheXpert-v1.0-small/train/patient00009/study1/...    Male   76   
18      CheXpert-v1.0-small/train/patient00010/study1/...  Female   50   
19      CheXpert-v1.0-small/train/patient00010/study1/...  Female   50   
20      CheXpert-v1.0-small/train/patient00011/study13...  Female   22   
21      CheXpert-v1.0-small/train/patient00011/study13...  Female   22   
22      CheXpert-v1.0-small/train/patient00011/study1/...  Female   19   
23      CheXpert-v1.0-small/train/patient00011/study5/...  Female   19   
24      CheXpert-v1.0-small/train/patient00011/study7/...  Female   19   
25      CheXpert-v1.0-small/train/patient00011/study4/...  Female   19   
26      CheXpert-v1.0-small/train/patient00011/study2/...  Female   19   
27      CheXpert-v1.0-small/train/patient00011/study10...  Female   19   
28      CheXpert-v1.0-small/train/patient00011/study9/...  Female   19   
29      CheXpert-v1.0-small/train/patient00011/study11...  Female   19   
...                                                   ...     ...  ...   
223384  CheXpert-v1.0-small/train/patient64515/study1/...    Male   25   
223385  CheXpert-v1.0-small/train/patient64516/study1/...  Female   75   
223386  CheXpert-v1.0-small/train/patient64517/study1/...    Male   21   
223387  CheXpert-v1.0-small/train/patient64518/study1/...    Male   68   
223388  CheXpert-v1.0-small/train/patient64519/study1/...  Female   33   
223389  CheXpert-v1.0-small/train/patient64520/study1/...  Female   65   
223390  CheXpert-v1.0-small/train/patient64521/study1/...  Female   63   
223391  CheXpert-v1.0-small/train/patient64522/study1/...  Female   21   
223392  CheXpert-v1.0-small/train/patient64523/study1/...  Female   90   
223393  CheXpert-v1.0-small/train/patient64524/study1/...  Female   61   
223394  CheXpert-v1.0-small/train/patient64525/study1/...    Male   87   
223395  CheXpert-v1.0-small/train/patient64526/study1/...    Male   55   
223396  CheXpert-v1.0-small/train/patient64527/study2/...    Male   85   
223397  CheXpert-v1.0-small/train/patient64527/study1/...    Male   85   
223398  CheXpert-v1.0-small/train/patient64528/study1/...    Male   77   
223399  CheXpert-v1.0-small/train/patient64529/study1/...    Male   81   
223400  CheXpert-v1.0-small/train/patient64530/study1/...    Male   65   
223401  CheXpert-v1.0-small/train/patient64531/study1/...  Female   57   
223402  CheXpert-v1.0-small/train/patient64532/study1/...  Female   52   
223403  CheXpert-v1.0-small/train/patient64533/study1/...    Male   75   
223404  CheXpert-v1.0-small/train/patient64533/study2/...    Male   75   
223405  CheXpert-v1.0-small/train/patient64534/study1/...    Male   63   
223406  CheXpert-v1.0-small/train/patient64535/study1/...

In [7]:
# get the columns
for i, col in enumerate(train_csv.columns):
    print(i, col)
    print(pd.unique(train_csv[col]))
    print(len(pd.unique(train_csv[col])))
    print("\n")

0 Path
['CheXpert-v1.0-small/train/patient00001/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient00002/study2/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient00002/study1/view1_frontal.jpg' ...
 'CheXpert-v1.0-small/train/patient64538/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64539/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64540/study1/view1_frontal.jpg']
223414


1 Sex
['Female' 'Male' 'Unknown']
3


2 Age
[68 87 83 41 20 33 42 69 81 76 50 22 19 61 55 36 43 54 56 44 46 63 59 62
 67 78 64 70 71 37 74 88 89 85 45 60 38 75 49 90 86 72 48 65 27 66 35 29
 80 79 39 25 51 18 77 53 23 31 21 40 58 84 47 52 82 73 30 57 24 28 32 34
 26  0]
74


3 Frontal/Lateral
['Frontal' 'Lateral']
2


4 AP/PA
['AP' nan 'PA' 'LL' 'RL']
5


5 No Finding
[ 1. nan]
2


6 Enlarged Cardiomediastinum
[nan  0.  1. -1.]
4


7 Cardiomegaly
[nan -1.  0.  1.]
4


8 Lung Opacity
[nan  1.  0. -1.]
4


9 Lung Lesion
[nan  1. -1.  0.]
4


10 Edema
[nan -1.  1.  0.]
4




According to [reddit discussion](https://www.reddit.com/r/MachineLearning/comments/aj7odi/r_introducing_chexpert_and_mimiccxr_datasets/) about the labels of this dataset, 1.0 is "positive", -1.0 is "uncertain", 0.0 is "negative", and blank is "not mentioned".

# Explore validation.csv

In [8]:
valid_csv_name = "/valid.csv"

In [9]:
# read the test.csv file
with open(root_path+valid_csv_name, "rt") as fin:
    valid_csv = pd.read_csv(fin)

In [10]:
valid_csv

Path     Sex  Age  \
0    CheXpert-v1.0-small/valid/patient64541/study1/...    Male   73   
1    CheXpert-v1.0-small/valid/patient64542/study1/...    Male   70   
2    CheXpert-v1.0-small/valid/patient64542/study1/...    Male   70   
3    CheXpert-v1.0-small/valid/patient64543/study1/...    Male   85   
4    CheXpert-v1.0-small/valid/patient64544/study1/...  Female   42   
5    CheXpert-v1.0-small/valid/patient64545/study1/...  Female   55   
6    CheXpert-v1.0-small/valid/patient64546/study1/...    Male   56   
7    CheXpert-v1.0-small/valid/patient64547/study1/...    Male   59   
8    CheXpert-v1.0-small/valid/patient64547/study1/...    Male   59   
9    CheXpert-v1.0-small/valid/patient64547/study1/...    Male   59   
10   CheXpert-v1.0-small/valid/patient64548/study1/...  Female   53   
11   CheXpert-v1.0-small/valid/patient64549/study1/...  Female   32   
12   CheXpert-v1.0-small/valid/patient64550/study1/...    Male   34   
13   CheXpert-v1.0-small/valid/patient64551/study1/...    Male   63   
14   CheXpert-v1.0-small/valid/patient64551/study1/...    Male   63   
15   CheXpert-v1.0-small/valid/patient64552/study1/...  Female   84   
16   CheXpert-v1.0-small/valid/patient64553/study1/...  Female   61   
17   CheXpert-v1.0-small/valid/patient64554/study1/...  Female   19   
18   CheXpert-v1.0-small/valid/patient64555/study1/...    Male   90   
19   CheXpert-v1.0-small/valid/patient64556/study1/...    Male   47   
20   CheXpert-v1.0-small/valid/patient64556/study1/...    Male   47   
21   CheXpert-v1.0-small/valid/patient64557/study1/...  Female   48   
22   CheXpert-v1.0-small/valid/patient64558/study1/...  Female   44   
23   CheXpert-v1.0-small/valid/patient64558/study1/...  Female   44   
24   CheXpert-v1.0-small/valid/patient64559/study1/...    Male   52   
25   CheXpert-v1.0-small/valid/patient64559/study1/...    Male   52   
26   CheXpert-v1.0-small/valid/patient64560/study1/...  Female   64   
27   CheXpert-v1.0-small/valid/patient64560/study1/...  Female   64   
28   CheXpert-v1.0-small/valid/patient64561/study1/...    Male   59   
29   CheXpert-v1.0-small/valid/patient64562/study1/...    Male   25   
..                                                 ...     ...  ...   
204  CheXpert-v1.0-small/valid/patient64711/study1/...  Female   80   
205  CheXpert-v1.0-small/valid/patient64712/study1/...  Female   75   
206  CheXpert-v1.0-small/valid/patient64713/study1/...  Female   76   
207  CheXpert-v1.0-small/valid/patient64714/study1/...    Male   63   
208  CheXpert-v1.0-small/valid/patient64715/study1/...    Male   81   
209  CheXpert-v1.0-small/valid/patient64716/study1/...  Female   68   
210  CheXpert-v1.0-small/valid/patient64717/study1/...    Male   90   
211  CheXpert-v1.0-small/valid/patient64718/study1/...    Male   83   
212  CheXpert-v1.0-small/valid/patient64719/study1/...    Male   68   
213  CheXpert-v1.0-small/valid/patient64720/study1/...  Female   77   
214  CheXpert-v1.0-small/valid/patient64721/study1/...    Male   67   
215  CheXpert-v1.0-small/valid/patient64722/study1/...  Female   81   
216  CheXpert-v1.0-small/valid/patient64723/study1/...    Male   77   
217  CheXpert-v1.0-small/valid/patient64724/study1/...  Female   54   
218  CheXpert-v1.0-small/valid/patient64725/study1/...    Male   75   
219  CheXpert-v1.0-small/valid/patient64726/study1/...    Male   60   
220  CheXpert-v1.0-small/valid/patient64727/study1/...  Female   59   
221  CheXpert-v1.0-small/valid/patient64728/study1/...    Male   76   
222  CheXpert-v1.0-small/valid/patient64729/study1/...    Male   72   
223  CheXpert-v1.0-small/valid/patient64730/study1/...  Female   36   
224  CheXpert-v1.0-small/valid/patient64731/study1/...    Male   60   
225  CheXpert-v1.0-small/valid/patient64732/study1/...  Female   49   
226  CheXpert-v1.0-small/valid/patient64733/study1/...    Male   87   
227  CheXpert-v1.0-small/valid/patient64734/study1/...    Male   45   
228  CheXpert-v1.0-small/valid/patient64735/study1/...  Female   63   
229

In [11]:
# get the columns
for i, col in enumerate(valid_csv.columns):
    print(i, col)
    print(pd.unique(valid_csv[col]))
    print(len(pd.unique(valid_csv[col])))
    print("\n")

0 Path
['CheXpert-v1.0-small/valid/patient64541/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64542/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64542/study1/view2_lateral.jpg'
 'CheXpert-v1.0-small/valid/patient64543/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64544/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64545/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64546/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64547/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64547/study1/view2_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64547/study1/view3_lateral.jpg'
 'CheXpert-v1.0-small/valid/patient64548/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64549/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64550/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64551/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/valid/patient64551/study1/view2_l

We can see from the validation set that there is no uncertainty labels.

# Explore the image data

In [12]:
import glob

In [13]:
train_patient_folders = glob.glob("/scratch/hw1666/final_projects/dl4med/data/train/patient*")

In [14]:
train_patient_folders

['/scratch/hw1666/final_projects/dl4med/data/train/patient31889',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient19887',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient01275',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient02624',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient30901',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient19703',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient19285',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient35001',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient13944',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient28667',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient07542',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient50655',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient16990',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient62764',
 '/scratch/hw1666/final_projects/dl4med/data/train/patient10807',
 '/scratch

In [15]:
len(train_patient_folders)

64540

# Preprocessing data in the training csv file

Simplestly, we fill all the NaN in the label column as 0.0 as negative. And then drop the administrative columns.

In [16]:
# first we drop the administrative columns
drop_columns = ["Sex", "Age", "AP/PA"]
train_csv = train_csv.drop(columns=drop_columns)

In [17]:
train_csv

Path Frontal/Lateral  \
0       CheXpert-v1.0-small/train/patient00001/study1/...         Frontal   
1       CheXpert-v1.0-small/train/patient00002/study2/...         Frontal   
2       CheXpert-v1.0-small/train/patient00002/study1/...         Frontal   
3       CheXpert-v1.0-small/train/patient00002/study1/...         Lateral   
4       CheXpert-v1.0-small/train/patient00003/study1/...         Frontal   
5       CheXpert-v1.0-small/train/patient00004/study1/...         Frontal   
6       CheXpert-v1.0-small/train/patient00004/study1/...         Lateral   
7       CheXpert-v1.0-small/train/patient00005/study1/...         Frontal   
8       CheXpert-v1.0-small/train/patient00005/study1/...         Lateral   
9       CheXpert-v1.0-small/train/patient00005/study2/...         Frontal   
10      CheXpert-v1.0-small/train/patient00005/study2/...         Frontal   
11      CheXpert-v1.0-small/train/patient00006/study1/...         Frontal   
12      CheXpert-v1.0-small/train/patient00007/study1/...         Frontal   
13      CheXpert-v1.0-small/train/patient00007/study2/...         Frontal   
14      CheXpert-v1.0-small/train/patient00008/study1/...         Frontal   
15      CheXpert-v1.0-small/train/patient00008/study2/...         Frontal   
16      CheXpert-v1.0-small/train/patient00009/study1/...         Frontal   
17      CheXpert-v1.0-small/train/patient00009/study1/...         Lateral   
18      CheXpert-v1.0-small/train/patient00010/study1/...         Frontal   
19      CheXpert-v1.0-small/train/patient00010/study1/...         Lateral   
20      CheXpert-v1.0-small/train/patient00011/study13...         Frontal   
21      CheXpert-v1.0-small/train/patient00011/study13...         Lateral   
22      CheXpert-v1.0-small/train/patient00011/study1/...         Frontal   
23      CheXpert-v1.0-small/train/patient00011/study5/...         Frontal   
24      CheXpert-v1.0-small/train/patient00011/study7/...         Frontal   
25      CheXpert-v1.0-small/train/patient00011/study4/...         Frontal   
26      CheXpert-v1.0-small/train/patient00011/study2/...         Frontal   
27      CheXpert-v1.0-small/train/patient00011/study10...         Frontal   
28      CheXpert-v1.0-small/train/patient00011/study9/...         Frontal   
29      CheXpert-v1.0-small/train/patient00011/study11...         Frontal   
...                                                   ...             ...   
223384  CheXpert-v1.0-small/train/patient64515/study1/...         Frontal   
223385  CheXpert-v1.0-small/train/patient64516/study1/...         Frontal   
223386  CheXpert-v1.0-small/train/patient64517/study1/...         Frontal   
223387  CheXpert-v1.0-small/train/patient64518/study1/...         Frontal   
223388  CheXpert-v1.0-small/train/patient64519/study1/...         Frontal   
223389  CheXpert-v1.0-small/train/patient64520/study1/...         Frontal   
223390  CheXpert-v1.0-small/train/patient64521/study1/...         Frontal   
223391  CheXpert-v1.0-small/train/patient64522/study1/...         Frontal   
223392  CheXpert-v1.0-small/train/patient64523/study1/...         Frontal   
223393  CheXpert-v1.0-small/train/patient64524/study1/...         Frontal   
223394  CheXpert-v1.0-small/train/patient64525/study1/...         Frontal   
223395  CheXpert-v1.0-small/train/patient64526/study1/...         Frontal   
223396  CheXpert-v1.0-small/train/patient64527/study2/...         Frontal   
223397  CheXpert-v1.0-small/train/patient64527/study1/...         Frontal   
223398  CheXpert-v1.0-small/train/patient64528/study1/...         Frontal   
223399  CheXpert-v1.0-small/train/patient64529/study1/...         Frontal   
223400  CheXpert-v1.0-small/train/patient64530/study1/...         Frontal   
223401  CheXpert-v1.0-small/train/patient64531/study1/...         Frontal   
223402  CheXpert-v1.0-small/train/patient64532/study1/...         Frontal   
223403  CheXpert-v1.0-small/train/patient64533/study1/...         Frontal   
223404  CheXpert-v1.0-small/train/patient64533/st

In [18]:
# fill all the NaN as 0.0
train_csv = train_csv.fillna(0)

In [19]:
train_csv

Path Frontal/Lateral  \
0       CheXpert-v1.0-small/train/patient00001/study1/...         Frontal   
1       CheXpert-v1.0-small/train/patient00002/study2/...         Frontal   
2       CheXpert-v1.0-small/train/patient00002/study1/...         Frontal   
3       CheXpert-v1.0-small/train/patient00002/study1/...         Lateral   
4       CheXpert-v1.0-small/train/patient00003/study1/...         Frontal   
5       CheXpert-v1.0-small/train/patient00004/study1/...         Frontal   
6       CheXpert-v1.0-small/train/patient00004/study1/...         Lateral   
7       CheXpert-v1.0-small/train/patient00005/study1/...         Frontal   
8       CheXpert-v1.0-small/train/patient00005/study1/...         Lateral   
9       CheXpert-v1.0-small/train/patient00005/study2/...         Frontal   
10      CheXpert-v1.0-small/train/patient00005/study2/...         Frontal   
11      CheXpert-v1.0-small/train/patient00006/study1/...         Frontal   
12      CheXpert-v1.0-small/train/patient00007/study1/...         Frontal   
13      CheXpert-v1.0-small/train/patient00007/study2/...         Frontal   
14      CheXpert-v1.0-small/train/patient00008/study1/...         Frontal   
15      CheXpert-v1.0-small/train/patient00008/study2/...         Frontal   
16      CheXpert-v1.0-small/train/patient00009/study1/...         Frontal   
17      CheXpert-v1.0-small/train/patient00009/study1/...         Lateral   
18      CheXpert-v1.0-small/train/patient00010/study1/...         Frontal   
19      CheXpert-v1.0-small/train/patient00010/study1/...         Lateral   
20      CheXpert-v1.0-small/train/patient00011/study13...         Frontal   
21      CheXpert-v1.0-small/train/patient00011/study13...         Lateral   
22      CheXpert-v1.0-small/train/patient00011/study1/...         Frontal   
23      CheXpert-v1.0-small/train/patient00011/study5/...         Frontal   
24      CheXpert-v1.0-small/train/patient00011/study7/...         Frontal   
25      CheXpert-v1.0-small/train/patient00011/study4/...         Frontal   
26      CheXpert-v1.0-small/train/patient00011/study2/...         Frontal   
27      CheXpert-v1.0-small/train/patient00011/study10...         Frontal   
28      CheXpert-v1.0-small/train/patient00011/study9/...         Frontal   
29      CheXpert-v1.0-small/train/patient00011/study11...         Frontal   
...                                                   ...             ...   
223384  CheXpert-v1.0-small/train/patient64515/study1/...         Frontal   
223385  CheXpert-v1.0-small/train/patient64516/study1/...         Frontal   
223386  CheXpert-v1.0-small/train/patient64517/study1/...         Frontal   
223387  CheXpert-v1.0-small/train/patient64518/study1/...         Frontal   
223388  CheXpert-v1.0-small/train/patient64519/study1/...         Frontal   
223389  CheXpert-v1.0-small/train/patient64520/study1/...         Frontal   
223390  CheXpert-v1.0-small/train/patient64521/study1/...         Frontal   
223391  CheXpert-v1.0-small/train/patient64522/study1/...         Frontal   
223392  CheXpert-v1.0-small/train/patient64523/study1/...         Frontal   
223393  CheXpert-v1.0-small/train/patient64524/study1/...         Frontal   
223394  CheXpert-v1.0-small/train/patient64525/study1/...         Frontal   
223395  CheXpert-v1.0-small/train/patient64526/study1/...         Frontal   
223396  CheXpert-v1.0-small/train/patient64527/study2/...         Frontal   
223397  CheXpert-v1.0-small/train/patient64527/study1/...         Frontal   
223398  CheXpert-v1.0-small/train/patient64528/study1/...         Frontal   
223399  CheXpert-v1.0-small/train/patient64529/study1/...         Frontal   
223400  CheXpert-v1.0-small/train/patient64530/study1/...         Frontal   
223401  CheXpert-v1.0-small/train/patient64531/study1/...         Frontal   
223402  CheXpert-v1.0-small/train/patient64532/study1/...         Frontal   
223403  CheXpert-v1.0-small/train/patient64533/study1/...         Frontal   
223404  CheXpert-v1.0-small/train/patient64533/st

In [51]:
# write train.csv into the file
file_path = "/scratch/hw1666/final_projects/dl4med/data/processed_data"
processed_train_csv_filename = "/train_drop_fill.csv"
train_csv.to_csv(file_path+processed_train_csv_filename, index=False)

# Read in the processed train.csv and divide it into two sets

since there is no test set in the original set, so here, we divide the whole training set into two parts: (1) training set (2) validation set. Meanwhile, we use the original validation set as the test set.

In [25]:
# read in the processed train.csv
with open(file_path+processed_train_csv_filename, "rt") as fin:
    train_csv_processed = pd.read_csv(fin)

In [26]:
train_csv_processed

Path Frontal/Lateral  \
0       CheXpert-v1.0-small/train/patient00001/study1/...         Frontal   
1       CheXpert-v1.0-small/train/patient00002/study2/...         Frontal   
2       CheXpert-v1.0-small/train/patient00002/study1/...         Frontal   
3       CheXpert-v1.0-small/train/patient00002/study1/...         Lateral   
4       CheXpert-v1.0-small/train/patient00003/study1/...         Frontal   
5       CheXpert-v1.0-small/train/patient00004/study1/...         Frontal   
6       CheXpert-v1.0-small/train/patient00004/study1/...         Lateral   
7       CheXpert-v1.0-small/train/patient00005/study1/...         Frontal   
8       CheXpert-v1.0-small/train/patient00005/study1/...         Lateral   
9       CheXpert-v1.0-small/train/patient00005/study2/...         Frontal   
10      CheXpert-v1.0-small/train/patient00005/study2/...         Frontal   
11      CheXpert-v1.0-small/train/patient00006/study1/...         Frontal   
12      CheXpert-v1.0-small/train/patient00007/study1/...         Frontal   
13      CheXpert-v1.0-small/train/patient00007/study2/...         Frontal   
14      CheXpert-v1.0-small/train/patient00008/study1/...         Frontal   
15      CheXpert-v1.0-small/train/patient00008/study2/...         Frontal   
16      CheXpert-v1.0-small/train/patient00009/study1/...         Frontal   
17      CheXpert-v1.0-small/train/patient00009/study1/...         Lateral   
18      CheXpert-v1.0-small/train/patient00010/study1/...         Frontal   
19      CheXpert-v1.0-small/train/patient00010/study1/...         Lateral   
20      CheXpert-v1.0-small/train/patient00011/study13...         Frontal   
21      CheXpert-v1.0-small/train/patient00011/study13...         Lateral   
22      CheXpert-v1.0-small/train/patient00011/study1/...         Frontal   
23      CheXpert-v1.0-small/train/patient00011/study5/...         Frontal   
24      CheXpert-v1.0-small/train/patient00011/study7/...         Frontal   
25      CheXpert-v1.0-small/train/patient00011/study4/...         Frontal   
26      CheXpert-v1.0-small/train/patient00011/study2/...         Frontal   
27      CheXpert-v1.0-small/train/patient00011/study10...         Frontal   
28      CheXpert-v1.0-small/train/patient00011/study9/...         Frontal   
29      CheXpert-v1.0-small/train/patient00011/study11...         Frontal   
...                                                   ...             ...   
223384  CheXpert-v1.0-small/train/patient64515/study1/...         Frontal   
223385  CheXpert-v1.0-small/train/patient64516/study1/...         Frontal   
223386  CheXpert-v1.0-small/train/patient64517/study1/...         Frontal   
223387  CheXpert-v1.0-small/train/patient64518/study1/...         Frontal   
223388  CheXpert-v1.0-small/train/patient64519/study1/...         Frontal   
223389  CheXpert-v1.0-small/train/patient64520/study1/...         Frontal   
223390  CheXpert-v1.0-small/train/patient64521/study1/...         Frontal   
223391  CheXpert-v1.0-small/train/patient64522/study1/...         Frontal   
223392  CheXpert-v1.0-small/train/patient64523/study1/...         Frontal   
223393  CheXpert-v1.0-small/train/patient64524/study1/...         Frontal   
223394  CheXpert-v1.0-small/train/patient64525/study1/...         Frontal   
223395  CheXpert-v1.0-small/train/patient64526/study1/...         Frontal   
223396  CheXpert-v1.0-small/train/patient64527/study2/...         Frontal   
223397  CheXpert-v1.0-small/train/patient64527/study1/...         Frontal   
223398  CheXpert-v1.0-small/train/patient64528/study1/...         Frontal   
223399  CheXpert-v1.0-small/train/patient64529/study1/...         Frontal   
223400  CheXpert-v1.0-small/train/patient64530/study1/...         Frontal   
223401  CheXpert-v1.0-small/train/patient64531/study1/...         Frontal   
223402  CheXpert-v1.0-small/train/patient64532/study1/...         Frontal   
223403  CheXpert-v1.0-small/train/patient64533/study1/...         Frontal   
223404  CheXpert-v1.0-small/train/patient64533/st

### divide the training set into training and validation set, note that there are no overlapping of patients between different sets.

Here, we make the validation size as that of original validation set. The intuition is that original paper thinks that the original validation size is enough for tuning the model, so we use the same size, while not decreasing the training set aggressively.

In [29]:
train_csv_processed[-234:]

Path Frontal/Lateral  \
223180  CheXpert-v1.0-small/train/patient64331/study1/...         Frontal   
223181  CheXpert-v1.0-small/train/patient64332/study1/...         Frontal   
223182  CheXpert-v1.0-small/train/patient64333/study1/...         Frontal   
223183  CheXpert-v1.0-small/train/patient64334/study1/...         Frontal   
223184  CheXpert-v1.0-small/train/patient64335/study1/...         Frontal   
223185  CheXpert-v1.0-small/train/patient64336/study1/...         Frontal   
223186  CheXpert-v1.0-small/train/patient64337/study1/...         Frontal   
223187  CheXpert-v1.0-small/train/patient64338/study1/...         Frontal   
223188  CheXpert-v1.0-small/train/patient64339/study1/...         Frontal   
223189  CheXpert-v1.0-small/train/patient64340/study1/...         Frontal   
223190  CheXpert-v1.0-small/train/patient64341/study1/...         Frontal   
223191  CheXpert-v1.0-small/train/patient64342/study1/...         Frontal   
223192  CheXpert-v1.0-small/train/patient64343/study1/...         Frontal   
223193  CheXpert-v1.0-small/train/patient64344/study1/...         Frontal   
223194  CheXpert-v1.0-small/train/patient64345/study1/...         Frontal   
223195  CheXpert-v1.0-small/train/patient64346/study1/...         Frontal   
223196  CheXpert-v1.0-small/train/patient64347/study1/...         Frontal   
223197  CheXpert-v1.0-small/train/patient64348/study1/...         Frontal   
223198  CheXpert-v1.0-small/train/patient64349/study1/...         Frontal   
223199  CheXpert-v1.0-small/train/patient64350/study2/...         Frontal   
223200  CheXpert-v1.0-small/train/patient64350/study1/...         Frontal   
223201  CheXpert-v1.0-small/train/patient64351/study1/...         Frontal   
223202  CheXpert-v1.0-small/train/patient64352/study1/...         Frontal   
223203  CheXpert-v1.0-small/train/patient64353/study1/...         Frontal   
223204  CheXpert-v1.0-small/train/patient64354/study1/...         Frontal   
223205  CheXpert-v1.0-small/train/patient64355/study1/...         Frontal   
223206  CheXpert-v1.0-small/train/patient64356/study1/...         Frontal   
223207  CheXpert-v1.0-small/train/patient64357/study1/...         Frontal   
223208  CheXpert-v1.0-small/train/patient64357/study1/...         Frontal   
223209  CheXpert-v1.0-small/train/patient64358/study1/...         Frontal   
...                                                   ...             ...   
223384  CheXpert-v1.0-small/train/patient64515/study1/...         Frontal   
223385  CheXpert-v1.0-small/train/patient64516/study1/...         Frontal   
223386  CheXpert-v1.0-small/train/patient64517/study1/...         Frontal   
223387  CheXpert-v1.0-small/train/patient64518/study1/...         Frontal   
223388  CheXpert-v1.0-small/train/patient64519/study1/...         Frontal   
223389  CheXpert-v1.0-small/train/patient64520/study1/...         Frontal   
223390  CheXpert-v1.0-small/train/patient64521/study1/...         Frontal   
223391  CheXpert-v1.0-small/train/patient64522/study1/...         Frontal   
223392  CheXpert-v1.0-small/train/patient64523/study1/...         Frontal   
223393  CheXpert-v1.0-small/train/patient64524/study1/...         Frontal   
223394  CheXpert-v1.0-small/train/patient64525/study1/...         Frontal   
223395  CheXpert-v1.0-small/train/patient64526/study1/...         Frontal   
223396  CheXpert-v1.0-small/train/patient64527/study2/...         Frontal   
223397  CheXpert-v1.0-small/train/patient64527/study1/...         Frontal   
223398  CheXpert-v1.0-small/train/patient64528/study1/...         Frontal   
223399  CheXpert-v1.0-small/train/patient64529/study1/...         Frontal   
223400  CheXpert-v1.0-small/train/patient64530/study1/...         Frontal   
223401  CheXpert-v1.0-small/train/patient64531/study1/...         Frontal   
223402  CheXpert-v1.0-small/train/patient64532/study1/...         Frontal   
223403  CheXpert-v1.0-small/train/patient64533/study1/...         Frontal   
223404  CheXpert-v1.0-small/train/patient64533/st

In [33]:
train_csv_processed.iloc[-235]

Path                          CheXpert-v1.0-small/train/patient64330/study1/...
Frontal/Lateral                                                         Frontal
No Finding                                                                    0
Enlarged Cardiomediastinum                                                    0
Cardiomegaly                                                                  0
Lung Opacity                                                                  0
Lung Lesion                                                                   0
Edema                                                                         1
Consolidation                                                                 0
Pneumonia                                                                     0
Atelectasis                                                                   1
Pneumothorax                                                                  0
Pleural Effusion                        

So we can see that there is no overlapping between two sets.

In [34]:
valid_splitted = train_csv_processed[-234:]
train_splitted = train_csv_processed[:-234]

In [35]:
train_splitted

Path Frontal/Lateral  \
0       CheXpert-v1.0-small/train/patient00001/study1/...         Frontal   
1       CheXpert-v1.0-small/train/patient00002/study2/...         Frontal   
2       CheXpert-v1.0-small/train/patient00002/study1/...         Frontal   
3       CheXpert-v1.0-small/train/patient00002/study1/...         Lateral   
4       CheXpert-v1.0-small/train/patient00003/study1/...         Frontal   
5       CheXpert-v1.0-small/train/patient00004/study1/...         Frontal   
6       CheXpert-v1.0-small/train/patient00004/study1/...         Lateral   
7       CheXpert-v1.0-small/train/patient00005/study1/...         Frontal   
8       CheXpert-v1.0-small/train/patient00005/study1/...         Lateral   
9       CheXpert-v1.0-small/train/patient00005/study2/...         Frontal   
10      CheXpert-v1.0-small/train/patient00005/study2/...         Frontal   
11      CheXpert-v1.0-small/train/patient00006/study1/...         Frontal   
12      CheXpert-v1.0-small/train/patient00007/study1/...         Frontal   
13      CheXpert-v1.0-small/train/patient00007/study2/...         Frontal   
14      CheXpert-v1.0-small/train/patient00008/study1/...         Frontal   
15      CheXpert-v1.0-small/train/patient00008/study2/...         Frontal   
16      CheXpert-v1.0-small/train/patient00009/study1/...         Frontal   
17      CheXpert-v1.0-small/train/patient00009/study1/...         Lateral   
18      CheXpert-v1.0-small/train/patient00010/study1/...         Frontal   
19      CheXpert-v1.0-small/train/patient00010/study1/...         Lateral   
20      CheXpert-v1.0-small/train/patient00011/study13...         Frontal   
21      CheXpert-v1.0-small/train/patient00011/study13...         Lateral   
22      CheXpert-v1.0-small/train/patient00011/study1/...         Frontal   
23      CheXpert-v1.0-small/train/patient00011/study5/...         Frontal   
24      CheXpert-v1.0-small/train/patient00011/study7/...         Frontal   
25      CheXpert-v1.0-small/train/patient00011/study4/...         Frontal   
26      CheXpert-v1.0-small/train/patient00011/study2/...         Frontal   
27      CheXpert-v1.0-small/train/patient00011/study10...         Frontal   
28      CheXpert-v1.0-small/train/patient00011/study9/...         Frontal   
29      CheXpert-v1.0-small/train/patient00011/study11...         Frontal   
...                                                   ...             ...   
223150  CheXpert-v1.0-small/train/patient64306/study1/...         Frontal   
223151  CheXpert-v1.0-small/train/patient64307/study1/...         Frontal   
223152  CheXpert-v1.0-small/train/patient64308/study1/...         Frontal   
223153  CheXpert-v1.0-small/train/patient64309/study1/...         Frontal   
223154  CheXpert-v1.0-small/train/patient64310/study1/...         Frontal   
223155  CheXpert-v1.0-small/train/patient64311/study1/...         Frontal   
223156  CheXpert-v1.0-small/train/patient64312/study1/...         Frontal   
223157  CheXpert-v1.0-small/train/patient64313/study1/...         Frontal   
223158  CheXpert-v1.0-small/train/patient64314/study3/...         Frontal   
223159  CheXpert-v1.0-small/train/patient64314/study1/...         Frontal   
223160  CheXpert-v1.0-small/train/patient64314/study2/...         Frontal   
223161  CheXpert-v1.0-small/train/patient64315/study1/...         Frontal   
223162  CheXpert-v1.0-small/train/patient64315/study2/...         Frontal   
223163  CheXpert-v1.0-small/train/patient64316/study1/...         Frontal   
223164  CheXpert-v1.0-small/train/patient64317/study1/...         Frontal   
223165  CheXpert-v1.0-small/train/patient64318/study1/...         Frontal   
223166  CheXpert-v1.0-small/train/patient64319/study1/...         Frontal   
223167  CheXpert-v1.0-small/train/patient64320/study1/...         Frontal   
223168  CheXpert-v1.0-small/train/patient64321/study1/...         Frontal   
223169  CheXpert-v1.0-small/train/patient64322/study1/...         Frontal   
223170  CheXpert-v1.0-small/train/patient64323/st

In [36]:
valid_splitted

Path Frontal/Lateral  \
223180  CheXpert-v1.0-small/train/patient64331/study1/...         Frontal   
223181  CheXpert-v1.0-small/train/patient64332/study1/...         Frontal   
223182  CheXpert-v1.0-small/train/patient64333/study1/...         Frontal   
223183  CheXpert-v1.0-small/train/patient64334/study1/...         Frontal   
223184  CheXpert-v1.0-small/train/patient64335/study1/...         Frontal   
223185  CheXpert-v1.0-small/train/patient64336/study1/...         Frontal   
223186  CheXpert-v1.0-small/train/patient64337/study1/...         Frontal   
223187  CheXpert-v1.0-small/train/patient64338/study1/...         Frontal   
223188  CheXpert-v1.0-small/train/patient64339/study1/...         Frontal   
223189  CheXpert-v1.0-small/train/patient64340/study1/...         Frontal   
223190  CheXpert-v1.0-small/train/patient64341/study1/...         Frontal   
223191  CheXpert-v1.0-small/train/patient64342/study1/...         Frontal   
223192  CheXpert-v1.0-small/train/patient64343/study1/...         Frontal   
223193  CheXpert-v1.0-small/train/patient64344/study1/...         Frontal   
223194  CheXpert-v1.0-small/train/patient64345/study1/...         Frontal   
223195  CheXpert-v1.0-small/train/patient64346/study1/...         Frontal   
223196  CheXpert-v1.0-small/train/patient64347/study1/...         Frontal   
223197  CheXpert-v1.0-small/train/patient64348/study1/...         Frontal   
223198  CheXpert-v1.0-small/train/patient64349/study1/...         Frontal   
223199  CheXpert-v1.0-small/train/patient64350/study2/...         Frontal   
223200  CheXpert-v1.0-small/train/patient64350/study1/...         Frontal   
223201  CheXpert-v1.0-small/train/patient64351/study1/...         Frontal   
223202  CheXpert-v1.0-small/train/patient64352/study1/...         Frontal   
223203  CheXpert-v1.0-small/train/patient64353/study1/...         Frontal   
223204  CheXpert-v1.0-small/train/patient64354/study1/...         Frontal   
223205  CheXpert-v1.0-small/train/patient64355/study1/...         Frontal   
223206  CheXpert-v1.0-small/train/patient64356/study1/...         Frontal   
223207  CheXpert-v1.0-small/train/patient64357/study1/...         Frontal   
223208  CheXpert-v1.0-small/train/patient64357/study1/...         Frontal   
223209  CheXpert-v1.0-small/train/patient64358/study1/...         Frontal   
...                                                   ...             ...   
223384  CheXpert-v1.0-small/train/patient64515/study1/...         Frontal   
223385  CheXpert-v1.0-small/train/patient64516/study1/...         Frontal   
223386  CheXpert-v1.0-small/train/patient64517/study1/...         Frontal   
223387  CheXpert-v1.0-small/train/patient64518/study1/...         Frontal   
223388  CheXpert-v1.0-small/train/patient64519/study1/...         Frontal   
223389  CheXpert-v1.0-small/train/patient64520/study1/...         Frontal   
223390  CheXpert-v1.0-small/train/patient64521/study1/...         Frontal   
223391  CheXpert-v1.0-small/train/patient64522/study1/...         Frontal   
223392  CheXpert-v1.0-small/train/patient64523/study1/...         Frontal   
223393  CheXpert-v1.0-small/train/patient64524/study1/...         Frontal   
223394  CheXpert-v1.0-small/train/patient64525/study1/...         Frontal   
223395  CheXpert-v1.0-small/train/patient64526/study1/...         Frontal   
223396  CheXpert-v1.0-small/train/patient64527/study2/...         Frontal   
223397  CheXpert-v1.0-small/train/patient64527/study1/...         Frontal   
223398  CheXpert-v1.0-small/train/patient64528/study1/...         Frontal   
223399  CheXpert-v1.0-small/train/patient64529/study1/...         Frontal   
223400  CheXpert-v1.0-small/train/patient64530/study1/...         Frontal   
223401  CheXpert-v1.0-small/train/patient64531/study1/...         Frontal   
223402  CheXpert-v1.0-small/train/patient64532/study1/...         Frontal   
223403  CheXpert-v1.0-small/train/patient64533/study1/...         Frontal   
223404  CheXpert-v1.0-small/train/patient64533/st

In [42]:
# get the unique values for each columns in train_splitted dataset
for i, col in enumerate(train_splitted.columns):
    print(i)
    print(col)
    print(pd.unique(train_splitted[col]))
    print("\n")

0
Path
['CheXpert-v1.0-small/train/patient00001/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient00002/study2/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient00002/study1/view1_frontal.jpg' ...
 'CheXpert-v1.0-small/train/patient64328/study2/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64329/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64330/study1/view1_frontal.jpg']


1
Frontal/Lateral
['Frontal' 'Lateral']


2
No Finding
[1. 0.]


3
Enlarged Cardiomediastinum
[ 0.  1. -1.]


4
Cardiomegaly
[ 0. -1.  1.]


5
Lung Opacity
[ 0.  1. -1.]


6
Lung Lesion
[ 0.  1. -1.]


7
Edema
[ 0. -1.  1.]


8
Consolidation
[ 0. -1.  1.]


9
Pneumonia
[ 0. -1.  1.]


10
Atelectasis
[ 0. -1.  1.]


11
Pneumothorax
[ 0.  1. -1.]


12
Pleural Effusion
[ 0. -1.  1.]


13
Pleural Other
[ 0.  1. -1.]


14
Fracture
[ 0.  1. -1.]


15
Support Devices
[ 1.  0. -1.]




In [43]:
# get the unique values for each columns in train_splitted dataset
for i, col in enumerate(valid_splitted.columns):
    print(i)
    print(col)
    print(pd.unique(valid_splitted[col]))
    print("\n")

0
Path
['CheXpert-v1.0-small/train/patient64331/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64332/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64333/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64334/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64335/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64336/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64337/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64338/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64339/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64340/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64341/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64342/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64343/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64344/study1/view1_frontal.jpg'
 'CheXpert-v1.0-small/train/patient64345/study1/view1_f

### shuffle them

In [44]:
train_splitted_shuffled = train_splitted.sample(frac=1).reset_index(drop=True)

In [45]:
valid_splitted_shuffled = valid_splitted.sample(frac=1).reset_index(drop=True)

In [46]:
train_splitted_shuffled

Path Frontal/Lateral  \
0       CheXpert-v1.0-small/train/patient27734/study10...         Frontal   
1       CheXpert-v1.0-small/train/patient37852/study3/...         Frontal   
2       CheXpert-v1.0-small/train/patient29905/study1/...         Frontal   
3       CheXpert-v1.0-small/train/patient29502/study2/...         Frontal   
4       CheXpert-v1.0-small/train/patient15058/study8/...         Frontal   
5       CheXpert-v1.0-small/train/patient50213/study2/...         Frontal   
6       CheXpert-v1.0-small/train/patient06258/study1/...         Frontal   
7       CheXpert-v1.0-small/train/patient57827/study1/...         Frontal   
8       CheXpert-v1.0-small/train/patient17476/study1/...         Frontal   
9       CheXpert-v1.0-small/train/patient27701/study8/...         Frontal   
10      CheXpert-v1.0-small/train/patient30701/study2/...         Frontal   
11      CheXpert-v1.0-small/train/patient27954/study1/...         Lateral   
12      CheXpert-v1.0-small/train/patient07364/study1/...         Frontal   
13      CheXpert-v1.0-small/train/patient50234/study1/...         Frontal   
14      CheXpert-v1.0-small/train/patient24972/study1/...         Frontal   
15      CheXpert-v1.0-small/train/patient49533/study1/...         Frontal   
16      CheXpert-v1.0-small/train/patient18263/study2/...         Frontal   
17      CheXpert-v1.0-small/train/patient34639/study2/...         Frontal   
18      CheXpert-v1.0-small/train/patient18767/study1/...         Frontal   
19      CheXpert-v1.0-small/train/patient17951/study1/...         Frontal   
20      CheXpert-v1.0-small/train/patient06051/study12...         Frontal   
21      CheXpert-v1.0-small/train/patient11258/study20...         Frontal   
22      CheXpert-v1.0-small/train/patient20762/study4/...         Frontal   
23      CheXpert-v1.0-small/train/patient10940/study3/...         Frontal   
24      CheXpert-v1.0-small/train/patient31684/study2/...         Frontal   
25      CheXpert-v1.0-small/train/patient47337/study3/...         Frontal   
26      CheXpert-v1.0-small/train/patient46210/study1/...         Frontal   
27      CheXpert-v1.0-small/train/patient22393/study7/...         Frontal   
28      CheXpert-v1.0-small/train/patient20195/study1/...         Frontal   
29      CheXpert-v1.0-small/train/patient32958/study1/...         Lateral   
...                                                   ...             ...   
223150  CheXpert-v1.0-small/train/patient30557/study4/...         Frontal   
223151  CheXpert-v1.0-small/train/patient44447/study1/...         Frontal   
223152  CheXpert-v1.0-small/train/patient35322/study2/...         Frontal   
223153  CheXpert-v1.0-small/train/patient00859/study1/...         Lateral   
223154  CheXpert-v1.0-small/train/patient40489/study1/...         Frontal   
223155  CheXpert-v1.0-small/train/patient24527/study17...         Frontal   
223156  CheXpert-v1.0-small/train/patient11167/study1/...         Frontal   
223157  CheXpert-v1.0-small/train/patient25190/study2/...         Frontal   
223158  CheXpert-v1.0-small/train/patient00550/study3/...         Frontal   
223159  CheXpert-v1.0-small/train/patient63625/study1/...         Frontal   
223160  CheXpert-v1.0-small/train/patient37448/study21...         Frontal   
223161  CheXpert-v1.0-small/train/patient48459/study1/...         Frontal   
223162  CheXpert-v1.0-small/train/patient47684/study2/...         Frontal   
223163  CheXpert-v1.0-small/train/patient01095/study1/...         Frontal   
223164  CheXpert-v1.0-small/train/patient15186/study1/...         Frontal   
223165  CheXpert-v1.0-small/train/patient03961/study1/...         Lateral   
223166  CheXpert-v1.0-small/train/patient35442/study6/...         Frontal   
223167  CheXpert-v1.0-small/train/patient31463/study4/...         Frontal   
223168  CheXpert-v1.0-small/train/patient10110/study4/...         Frontal   
223169  CheXpert-v1.0-small/train/patient33588/study1/...         Frontal   
223170  CheXpert-v1.0-small/train/patient15147/st

In [47]:
valid_splitted_shuffled

Path Frontal/Lateral  \
0    CheXpert-v1.0-small/train/patient64369/study1/...         Frontal   
1    CheXpert-v1.0-small/train/patient64345/study1/...         Frontal   
2    CheXpert-v1.0-small/train/patient64499/study1/...         Frontal   
3    CheXpert-v1.0-small/train/patient64360/study1/...         Frontal   
4    CheXpert-v1.0-small/train/patient64419/study1/...         Frontal   
5    CheXpert-v1.0-small/train/patient64491/study2/...         Frontal   
6    CheXpert-v1.0-small/train/patient64515/study1/...         Frontal   
7    CheXpert-v1.0-small/train/patient64411/study1/...         Frontal   
8    CheXpert-v1.0-small/train/patient64442/study1/...         Frontal   
9    CheXpert-v1.0-small/train/patient64498/study1/...         Frontal   
10   CheXpert-v1.0-small/train/patient64388/study1/...         Frontal   
11   CheXpert-v1.0-small/train/patient64487/study1/...         Frontal   
12   CheXpert-v1.0-small/train/patient64371/study1/...         Frontal   
13   CheXpert-v1.0-small/train/patient64374/study1/...         Frontal   
14   CheXpert-v1.0-small/train/patient64536/study2/...         Frontal   
15   CheXpert-v1.0-small/train/patient64478/study1/...         Frontal   
16   CheXpert-v1.0-small/train/patient64509/study1/...         Frontal   
17   CheXpert-v1.0-small/train/patient64463/study1/...         Frontal   
18   CheXpert-v1.0-small/train/patient64514/study1/...         Frontal   
19   CheXpert-v1.0-small/train/patient64508/study1/...         Frontal   
20   CheXpert-v1.0-small/train/patient64489/study1/...         Frontal   
21   CheXpert-v1.0-small/train/patient64379/study2/...         Frontal   
22   CheXpert-v1.0-small/train/patient64532/study1/...         Frontal   
23   CheXpert-v1.0-small/train/patient64475/study1/...         Frontal   
24   CheXpert-v1.0-small/train/patient64436/study1/...         Frontal   
25   CheXpert-v1.0-small/train/patient64400/study1/...         Frontal   
26   CheXpert-v1.0-small/train/patient64384/study1/...         Frontal   
27   CheXpert-v1.0-small/train/patient64355/study1/...         Frontal   
28   CheXpert-v1.0-small/train/patient64462/study2/...         Frontal   
29   CheXpert-v1.0-small/train/patient64490/study1/...         Frontal   
..                                                 ...             ...   
204  CheXpert-v1.0-small/train/patient64440/study1/...         Frontal   
205  CheXpert-v1.0-small/train/patient64537/study1/...         Frontal   
206  CheXpert-v1.0-small/train/patient64504/study1/...         Frontal   
207  CheXpert-v1.0-small/train/patient64536/study1/...         Frontal   
208  CheXpert-v1.0-small/train/patient64531/study1/...         Frontal   
209  CheXpert-v1.0-small/train/patient64446/study1/...         Frontal   
210  CheXpert-v1.0-small/train/patient64470/study1/...         Frontal   
211  CheXpert-v1.0-small/train/patient64415/study1/...         Frontal   
212  CheXpert-v1.0-small/train/patient64393/study1/...         Frontal   
213  CheXpert-v1.0-small/train/patient64457/study1/...         Frontal   
214  CheXpert-v1.0-small/train/patient64468/study1/...         Frontal   
215  CheXpert-v1.0-small/train/patient64480/study1/...         Frontal   
216  CheXpert-v1.0-small/train/patient64516/study1/...         Frontal   
217  CheXpert-v1.0-small/train/patient64474/study1/...         Frontal   
218  CheXpert-v1.0-small/train/patient64395/study1/...         Frontal   
219  CheXpert-v1.0-small/train/patient64483/study2/...         Frontal   
220  CheXpert-v1.0-small/train/patient64533/study2/...         Frontal   
221  CheXpert-v1.0-small/train/patient64464/study1/...         Frontal   
222  CheXpert-v1.0-small/train/patient64471/study1/...         Frontal   
223  CheXpert-v1.0-small/train/patient64357/study1/...         Frontal   
224  CheXpert-v1.0-small/train/patient64526/study1/...         Frontal   
225  CheXpert-v1.0-small/train/patient64386/study1/...         Frontal   
226  CheXpert-v1.0-small/train/patient64540/study1/...

In [52]:
# write them into the files
file_path = "/scratch/hw1666/final_projects/dl4med/data/processed_data"
train_filename = "/train_splitted_shuffle.csv"
valid_filename = "/valid_splitted_shuffel.csv"
train_splitted_shuffled.to_csv(file_path+train_filename, index=None)
valid_splitted_shuffled.to_csv(file_path+valid_filename, index=None)